
# test:
#   path : /test/{age<\d+>?0}
#   controller: App\Controller\TestController::test
#   methods: [GET , POST]
#   schemes : [https, http]
  # host: www.monsite.com / monsite.com / api.monsite.com ou {subdomain}.monsite.com // permet de limiter l'entrer sur le site avec uniquement ces noms.
  # defaults:
  #   age: 0
  # requirements:
  #   age: \d+